global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "alert_rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Node Exporter for system metrics
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  # Redis metrics
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']

  # PostgreSQL metrics
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']

  # User Service metrics
  - job_name: 'user-service'
    static_configs:
      - targets: ['user-service:3000']
    metrics_path: '/metrics'
    scrape_interval: 5s

  # Restaurant Service metrics
  - job_name: 'restaurant-service'
    static_configs:
      - targets: ['restaurant-service:3001']
    metrics_path: '/metrics'
    scrape_interval: 5s

  # Delivery Service metrics
  - job_name: 'delivery-service'
    static_configs:
      - targets: ['delivery-service:3002']
    metrics_path: '/metrics'
    scrape_interval: 5s

  # Kafka metrics (if using JMX exporter)
  - job_name: 'kafka'
    static_configs:
      - targets: ['kafka:9308']
