version: '3.8'

services:
  food-delivery-api:
    build:
      context: ./production
      dockerfile: Dockerfile
    container_name: food-delivery-api-prod
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3000/health', (res) => { process.exit(res.statusCode === 200 ? 0 : 1) })"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - food-delivery-network

networks:
  food-delivery-network:
    driver: bridge
